name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm i
          npm run build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: vap-dist
          path: dist

  Deploy-ghpages:
    needs: [Build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download dist artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: vap-dist
          path: dist

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Deploy-Firebase:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download dist artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: vap-dist
          path: dist

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VAP1_8D6C5 }}"
          channelId: live
          projectId: vap1-8d6c5

  Cleanup:
    needs: [Deploy-ghpages, Deploy-Firebase]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Delete dist artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: vap-dist
